workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build IPA
        script: flutter build ipa --release
      - flutter build ios --verbose
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: 
          key_id: YCWNM795Q9
          issuer_id: 17977e09-54b9-4a8c-bd91-5739f74989da
          private_key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZRzMNko2vbOWQgDw1kpIxApTlr3A1X6MJnhrVzdiyMigCgYIKoZIzj0DAQehRANCAAQnD/DakFiQbMVnpTozjOlH+nzu4zwoE4zfboC4jx26saRir7FOTtYKRp64/GRlQsPLwn11z4Leq0MwNtKLt9o7
